item {
    id: 1
    name: 'buffet'
}

item {
    id: 2
    name: 'coin'
}

item {
    id: 3
    name: 'glass'
}

item {
    id: 4
    name: 'sofa'
}

item {
    id: 5
    name: 'watch'
}

item {
    id: 6
    name: 'backpack'
}

item {
    id: 7
    name: 'umbrella'
}

item {
    id: 8
    name: 'handbag'
}

item {
    id: 9
    name: 'bottle'
}

item {
    id: 10
    name: 'cup'
}

item {
    id: 11
    name: 'fork'
}

item {
    id: 12
    name: 'knife'
}

item {
    id: 13
    name: 'spoon'
}

item {
    id: 14
    name: 'bowl'
}

item {
    id: 15
    name: 'dining_table'
}

item {
    id: 16
    name: 'laptop'
}

item {
    id: 17
    name: 'mouse'
}

item {
    id: 18
    name: 'remote'
}

item {
    id: 19
    name: 'keyboard'
}

item {
    id: 20
    name: 'scissors'
}

item {
    id: 21
    name: 'book'
}
item {
    id: 22
    name: 'coffee_table'
}
item {
    id: 23
    name: 'kleenex'
}
item {
    id: 24
    name: 'glasses'
}
item {
    id: 25
    name: 'dog_leash'
}
item {
    id: 26
    name: 'cigarette'
}

